AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This example demonstrates how to use Lambda Logs API, parse record fields, and convert them into OpenTelemetry metrics.

Globals:
  Function:
    Tags:
      project: "zakharovvi/aws-lambda-extensions"

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-logs-opentelemetry-metrics
      Description: This example demonstrates how to use Lambda Logs API, parse record fields, and convert them into OpenTelemetry metrics.
      CodeUri: function
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Architectures:
        - x86_64
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Layers:
        - !Ref ExtensionLayer
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-SAM-CLI.html
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
      Tags:
        project: zakharovvi/aws-lambda-extensions
  ExtensionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: example-logs-opentelemetry-metrics
      Description: Example Logs API to OpenTelemetry Metric Extension
      CompatibleArchitectures:
        - x86_64
      ContentUri: extension
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

Outputs:
  ExampleFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ExampleFunction.Arn
