build-ExtensionLayer:
	GOOS=linux GOARCH=amd64 go build -o $(ARTIFACTS_DIR)/extensions/logs-opentelemetry-metrics-extension main.go
	chmod +x $(ARTIFACTS_DIR)/extensions/logs-opentelemetry-metrics-extension
