version = 0.1

[default]

[default.build]
[default.build.parameters]
cached = "true"
parallel = "true"

[default.sync]
[default.sync.parameters]
stack_name = "example-internal-extension"
s3_bucket = "ci-aws-lambda-extensions-samreleasesbucketff04fc4-fehwm0914oha"
s3_prefix = "example-internal-extension"

[default.deploy]
[default.deploy.parameters]
stack_name = "example-internal-extension"
s3_bucket = "ci-aws-lambda-extensions-samreleasesbucketff04fc4-fehwm0914oha"
s3_prefix = "example-internal-extension"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
