AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample internal-extension demonstrates how to run an extension in the same binary with a lambda function.

Globals:
  Function:
    Tags:
      project: "zakharovvi/aws-lambda-extensions"

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-internal-extension
      Description: Sample internal-extension demonstrates how to run an extension in the same binary with a lambda function.
      CodeUri: .
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Architectures:
        - x86_64
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Layers:
        # https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-SAM-CLI.html
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"

Outputs:
  ExampleFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ExampleFunction.Arn
