name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --verbose

  test-runtime-interface-emulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./tests/rie/go.mod
      - name: Download RIE
        run: |
          curl -Lo /tmp/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie
          chmod +x /tmp/aws-lambda-rie
      - name: Run Test
        working-directory: ./tests/rie
        run: |
          go build -v ./...
          go test ./...

  test-examples-lambda-invoke:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::008697144133:role/ci-aws-lambda-extensions-githubactionsrole82740668-W46JYWTVLGNW
          aws-region: eu-west-1
      - uses: actions/cache@v3
        with:
          path: ./examples/*/.aws-sam
          key: constant
      - name: Run Test
        working-directory: ./tests/lambda
        run: |
          go test ./...

  cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: synth
          working_dir: cdk
